### PR TITLE
fix: add proper web link behavior in sidebar

### LINKED ISSUE #634: Navbar links are not anchors
(web app v0.7.33)
The links/icons in the navigation drawer seem to navigate by an onclick event and don't contain anchor elements. This stops the browser from showing a right click menu ("open in new tab" etc.) and could produce a worse ux with accessibility tools.

### PR DESCRIPTION
**Pull request by espeon**
Should close #634, there should be proper anchors in sidebar links

image

### CODE REVIEW

File: js/app/components/sidebar/sidebar-item.tsx [hunk 1]
```diff
@@ -1,19 +1,25 @@
...
+  GestureResponderEvent,
+  Pressable,
   PressableStateCallbackType,
   StyleProp,
   View,
   ViewStyle,
 } from "react-native";
-import { Pressable } from "react-native-gesture-handler";
+
+import {} from "src/router";
```
Comment (iameli) [inline js/app/components/sidebar/sidebar-item.tsx]: ?

**Review by iameli — APPROVED** [review]
Looks fine aside from probably-accidental import?

File: js/app/components/sidebar/sidebar-item.tsx (hunk 1 above)
Comment (espeon) [reply js/app/components/sidebar/sidebar-item.tsx]: Ah whoops, surprising that persisted 🤔
