### PR TITLE
fix: buttons with invalid/missing routes don't redirect home

### LINKED ISSUE #647: clicking on "documentation" redirects you back to home

### PR DESCRIPTION
**Pull request by espeon**

### CODE REVIEW

File: js/app/components/sidebar/sidebar-item.tsx [hunk 1]
```diff
@@ -91,7 +91,7 @@ export default function SidebarItem({
       role="link"
       accessibilityLabel={typeof label === "string" ? label : "Link to " + href}
       // @ts-ignore This makes it render as <a> on web!
-      href={href}
+      href={route && href}
```
Comment (iameli) [inline js/app/components/sidebar/sidebar-item.tsx]: This'll be `href={false}` if it doesn't exist which is a little weird. Maybe:
```suggestion
      href={route ? href : undefined}
```

**Review by iameli — CHANGES_REQUESTED** [review]
small thing
