### PR TITLE
fix: don't crash when labeler firehose is not available

### LINKED ISSUE #765: Don't crash when labeler firehose is unavailable
Set off alarms? Sure. Crashloop the node entirely? Nah.

### PR DESCRIPTION
**Pull request by ElshadHu**
### Description

I fixed an issue where labeler firehose connection failures could crash. I also added a Prometheus metric so I can observe labeler connections and implemented a graceful retry loop with backoff instead of crashing.

### Changes

- I added a `streamplace_labeler_firehoses_connected ` gauge metric in `spmetrics.go` to track labeler connections.
-  I used this metric to represent the connection state per labeler DID, where 1 means connected and 0 means disconnected.
-  I also changed the log level at the retry threshold from `Error` to `Warn`

### Testing

- I tested the change locally using Bluesky’s official moderation labeler
- I confirmed that the metric reports 1 while the labeler firehose is connected.
- Also I did the retry path and saw that the code backs off for 5 seconds after repeated failures instead of crashing the node.

Closes #765 

If there is any issue, please, let me know.

### CODE REVIEW

File: pkg/atproto/labeler_firehose.go [hunk 1]
```diff
@@ -107,7 +110,8 @@ func (atsync *ATProtoSynchronizer) StartLabelerFirehoseRetry(ctx context.Context
 	if err != nil {
 		return fmt.Errorf("subscribing to firehose failed (dialing): %w", err)
 	}
-
+	spmetrics.LabelerFirehosesConnected.WithLabelValues(did).Set(1)
+	defer spmetrics.LabelerFirehosesConnected.WithLabelValues(did).Set(0)
```
Comment (iameli) [inline pkg/atproto/labeler_firehose.go]: We can connect to more than one labeler firehose, so this should be `Inc` and `Dec` instead of `Set`

**Review by iameli — CHANGES_REQUESTED** [review]
Small change, looks okay

File: pkg/atproto/labeler_firehose.go (hunk 1 above)
Comment (ElshadHu) [reply pkg/atproto/labeler_firehose.go]: Thanks! I changed to `Inc` and `Dec`

**Review by iameli — APPROVED** [review]

**Comment by iameli** [comment]
thanks!
